[versions]
agp = "8.7.2"
kotlin = "2.0.20"
junit = "4.13.2"
extjunit = "1.2.1"
espresso = "3.6.1"
appcompat = "1.6.1"
material = "1.8.0"
activity = "1.7.2"
constraintlayout = "2.1.4"
core = "1.9.0"
recyclerview = "1.3.0"
cardview = "1.0.0"
maps = "19.2.0"
location = "21.0.1"
viewpager2 = "1.0.0"
fragment = "1.6.1"
swiperefreshlayout = "1.1.0"
mapbox = "11.13.1"
firebase-bom = "32.7.0"
play-services-maps = "18.2.0"
play-services-location = "21.0.1"
android-mail = "1.6.7"
android-activation = "1.6.7"
mpandroidchart = "3.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
extjunit = { group = "androidx.test.ext", name = "junit", version.ref = "extjunit" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "maps" }
location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "location" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
mapbox = { group = "com.mapbox.maps", name = "android", version.ref = "mapbox" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "play-services-maps" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
android-mail = { group = "com.sun.mail", name = "android-mail", version.ref = "android-mail" }
android-activation = { group = "com.sun.mail", name = "android-activation", version.ref = "android-activation" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
